import { 
  Profile, Group, Lesson, Homework, 
  HomeworkSubmission, DailyWord, WordProgress, ChampionshipScore, Badge 
} from '../types';

export const SEED_PROFILES: Profile[] = [
  {
    id: 'user-admin-1',
    email: 'admin@premier.uz',
    full_name: 'Nodirjon Safoyev (Admin)',
    role: 'admin',
    password: 'premier2026!',
    phone: '+998 90 123 45 67',
    age: 28,
    goal: 'Premier School Operations & Academic Quality',
    level: 'C2',
    onboarding_completed: true,
    xp: 5000,
    streak: 30,
    created_at: '2025-01-10T09:00:00Z',
  },
  {
    id: 'user-admin-2',
    email: 'nodirjon98@gmail.com',
    full_name: 'Nodirjon Safoyev (Admin)',
    role: 'admin',
    password: 'premier2026!',
    phone: '+998 90 123 45 67',
    age: 28,
    goal: 'Premier School Admin',
    level: 'C2',
    onboarding_completed: true,
    xp: 5000,
    streak: 30,
    created_at: '2025-01-10T09:00:00Z',
  },
  {
    id: 'user-admin-3',
    email: 'safoyevnodirjon@gmail.com',
    full_name: 'Nodirjon Safoyev (Admin)',
    role: 'admin',
    password: 'premier2026!',
    phone: '+998 90 123 45 67',
    age: 28,
    goal: 'Premier School Founder',
    level: 'C2',
    onboarding_completed: true,
    xp: 5000,
    streak: 30,
    created_at: '2025-01-10T09:00:00Z',
  },
  {
    id: 'user-teacher-1',
    email: 'teacher@premierschool.uz',
    full_name: 'Malika Karimova (CELTA)',
    role: 'teacher',
    phone: '+998 97 765 43 21',
    age: 29,
    goal: 'IELTS 8.5 Masterclasses',
    level: 'C1',
    onboarding_completed: true,
    xp: 2890,
    streak: 19,
    created_at: '2025-01-12T10:00:00Z',
  },
  {
    id: 'user-student-1',
    email: 'student@premierschool.uz',
    full_name: 'Jasur Rustamov',
    role: 'student',
    phone: '+998 93 555 11 22',
    age: 19,
    goal: 'Score IELTS 7.5 for Westminster University in Tashkent',
    level_estimate: 'B1',
    level: 'B2',
    schedule_preference: 'Mon / Wed / Fri 18:30 - 20:00',
    onboarding_completed: true,
    xp: 1420,
    streak: 12,
    created_at: '2025-02-01T14:00:00Z',
  },
  {
    id: 'user-student-2',
    email: 'nodira.k@gmail.com',
    full_name: 'Nodira Karimova',
    role: 'student',
    phone: '+998 99 888 77 66',
    age: 21,
    goal: 'Master conversational fluency for IT outsourcing',
    level: 'B2',
    onboarding_completed: true,
    xp: 1890,
    streak: 16,
    created_at: '2025-02-05T12:00:00Z',
  },
  {
    id: 'user-student-3',
    email: 'bekzod.t@gmail.com',
    full_name: 'Bekzod Toshmatov',
    role: 'student',
    phone: '+998 94 333 44 55',
    age: 18,
    goal: 'Grammar and academic writing for WIUT',
    level: 'B1',
    onboarding_completed: true,
    xp: 1210,
    streak: 8,
    created_at: '2025-02-10T12:00:00Z',
  }
];

export const SEED_GROUPS: Group[] = [
  {
    id: 'group-1',
    name: 'IELTS Intensive Target 7.5+',
    level: 'B2',
    teacher_id: 'user-teacher-1',
    teacher_name: 'Malika Karimova (CELTA)',
    schedule: 'Mon / Wed / Fri 18:30',
    room: 'Room 304 (Chorsu Campus)',
    created_at: '2025-02-01T10:00:00Z',
    students_count: 14,
  },
  {
    id: 'group-2',
    name: 'General English Intermediate B1',
    level: 'B1',
    teacher_id: 'user-teacher-1',
    teacher_name: 'Malika Karimova (CELTA)',
    schedule: 'Tue / Thu / Sat 16:30',
    room: 'Room 201 (Oybek Campus)',
    created_at: '2025-02-03T11:00:00Z',
    students_count: 12,
  },
  {
    id: 'group-3',
    name: 'Elementary English Starters A2',
    level: 'A2',
    teacher_id: 'user-teacher-1',
    teacher_name: 'Malika Karimova (CELTA)',
    schedule: 'Mon / Wed / Fri 10:00',
    room: 'Room 102 (Oybek Campus)',
    created_at: '2025-02-05T09:00:00Z',
    students_count: 10,
  }
];

export const SEED_LESSONS: Lesson[] = [
  {
    id: 'lesson-1',
    group_id: 'group-1',
    title: 'IELTS Writing Task 2: Advanced Coherence & Cohesion',
    topic: 'Linking words, concession clauses, paragraph structure',
    lesson_date: new Date().toISOString(),
    materials_url: 'https://example.com/materials/ielts-writing-task2.pdf',
    materials_name: 'IELTS_Band8_Writing_Guide.pdf',
    notes: 'Focus on topic sentences and avoiding repetitive connectors (furthermore, moreover).',
    created_at: '2025-02-15T08:00:00Z',
    group_name: 'IELTS Intensive Target 7.5+',
  },
  {
    id: 'lesson-2',
    group_id: 'group-1',
    title: 'Conditionals in Academic Speaking & Debate',
    topic: 'Third & Mixed Conditionals in hypothetical arguments',
    lesson_date: new Date(Date.now() + 86400000 * 2).toISOString(),
    materials_name: 'Conditionals_Cheatsheet.pdf',
    notes: 'Prepare a 2-minute speech on technological shifts in Central Asia.',
    created_at: '2025-02-16T08:00:00Z',
    group_name: 'IELTS Intensive Target 7.5+',
  },
  {
    id: 'lesson-3',
    group_id: 'group-2',
    title: 'Present Perfect vs Past Simple in Job Interviews',
    topic: 'Describing past life experiences and recent results',
    lesson_date: new Date().toISOString(),
    materials_name: 'Interview_Grammar_Mastery.pdf',
    notes: 'Pair work drills: answering interview questions.',
    created_at: '2025-02-15T08:00:00Z',
    group_name: 'General English Intermediate B1',
  }
];

export const SEED_HOMEWORK: Homework[] = [
  {
    id: 'hw-1',
    group_id: 'group-1',
    teacher_id: 'user-teacher-1',
    title: 'Task 2 Essay: Urbanization in Tashkent',
    description: 'Write a 250+ word discussion essay analyzing the advantages and disadvantages of high-rise construction.',
    due_date: new Date(Date.now() + 86400000 * 3).toISOString(),
    type: 'writing',
    content: {
      prompt: 'In recent years, modern high-rise buildings and commercial centers have rapidly replaced historic neighborhoods in Tashkent. Discuss both views and give your own opinion.',
      instructions: 'Ensure at least 4 paragraphs: Introduction, Body 1 (modern infrastructure), Body 2 (cultural heritage), and Conclusion. Target vocabulary: gentrification, sustainable, architectural heritage.'
    },
    max_score: 100,
    created_at: '2025-02-18T10:00:00Z',
    group_name: 'IELTS Intensive Target 7.5+',
    teacher_name: 'Malika Karimova (CELTA)'
  },
  {
    id: 'hw-2',
    group_id: 'group-1',
    teacher_id: 'user-teacher-1',
    title: 'Advanced Inversion & Emphasis Quiz',
    description: 'Auto-graded assessment on negative inversions (Rarely have I..., Not only did...).',
    due_date: new Date(Date.now() + 86400000 * 1).toISOString(),
    type: 'multiple_choice',
    content: {
      questions: [
        {
          id: 'q1',
          question: 'Seldom ______ such determination from young scholars in Uzbekistan.',
          options: ['we have seen', 'have we seen', 'we saw', 'did we saw'],
          correct_answer: 'have we seen',
          points: 25
        },
        {
          id: 'q2',
          question: 'Not until the exam results were published ______ his scholarship.',
          options: ['he confirmed', 'did he confirm', 'has he confirmed', 'he had confirmed'],
          correct_answer: 'did he confirm',
          points: 25
        },
        {
          id: 'q3',
          question: 'Under no circumstances ______ reveal your exam credentials to third parties.',
          options: ['you should', 'should you', 'you must', 'shall you'],
          correct_answer: 'should you',
          points: 25
        },
        {
          id: 'q4',
          question: 'Hardly ______ home when the torrential rain began over Amir Timur Square.',
          options: ['had I reached', 'I reached', 'did I reach', 'have I reached'],
          correct_answer: 'had I reached',
          points: 25
        }
      ]
    },
    max_score: 100,
    created_at: '2025-02-17T11:00:00Z',
    group_name: 'IELTS Intensive Target 7.5+',
    teacher_name: 'Malika Karimova (CELTA)'
  },
  {
    id: 'hw-3',
    group_id: 'group-1',
    teacher_id: 'user-teacher-1',
    title: 'Academic Collocations Gap Fill',
    description: 'Fill in the blanks with appropriate academic verbs and adjectives.',
    due_date: new Date(Date.now() + 86400000 * 4).toISOString(),
    type: 'fill_in_gap',
    content: {
      questions: [
        {
          id: 'fg-1',
          question: 'The research team conducted extensive studies to ______ valid evidence. (provide / yield / gain)',
          correct_answer: 'yield',
          points: 50
        },
        {
          id: 'fg-2',
          question: 'Education plays a ______ role in economic prosperity. (pivotal / trivial / fragile)',
          correct_answer: 'pivotal',
          points: 50
        }
      ]
    },
    max_score: 100,
    created_at: '2025-02-16T12:00:00Z',
    group_name: 'IELTS Intensive Target 7.5+',
    teacher_name: 'Malika Karimova (CELTA)'
  }
];

export const SEED_SUBMISSIONS: HomeworkSubmission[] = [
  {
    id: 'sub-1',
    homework_id: 'hw-2',
    student_id: 'user-student-1',
    submission_data: {
      answers: {
        'q1': 'have we seen',
        'q2': 'did he confirm',
        'q3': 'should you',
        'q4': 'had I reached'
      },
      submitted_at: '2025-02-18T16:20:00Z'
    },
    score: 100,
    auto_graded: true,
    status: 'graded',
    is_late: false,
    feedback: 'Flawless accuracy! Excellent command of formal negative inversion.',
    graded_at: '2025-02-18T16:20:00Z',
    submitted_at: '2025-02-18T16:20:00Z',
    homework_title: 'Advanced Inversion & Emphasis Quiz',
    student_name: 'Jasur Rustamov',
    max_score: 100
  }
];

export const SEED_DAILY_WORDS: DailyWord[] = [
  {
    id: 'word-1',
    word: 'Resilient',
    translation_uz: 'Bardoshli, chidamli, tez o\'zini o\'nglab oladigan',
    definition: 'Able to withstand or recover quickly from difficult conditions.',
    example: 'The students remained resilient despite the rigorous preparation schedule for IELTS.',
    cefr_level: 'B2',
    part_of_speech: 'adjective',
    phonetic: '/rɪˈzɪliənt/',
    day_index: 1,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'word-2',
    word: 'Eloquent',
    translation_uz: 'Fasohotli, notiq, chiroyli va ta\'sirli so\'zlovchi',
    definition: 'Fluent or persuasive in speaking or writing.',
    example: 'She gave an eloquent presentation about cultural tourism in Samarkand and Bukhara.',
    cefr_level: 'B2',
    part_of_speech: 'adjective',
    phonetic: '/ˈeləkwənt/',
    day_index: 1,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'word-3',
    word: 'Persevere',
    translation_uz: 'Sabr-matonat ko\'rsatmoq, qat\'iyat bilan davom etmoq',
    definition: 'Continue in a course of action even in the face of difficulty or with little prospect of success.',
    example: 'If you persevere with daily vocabulary reviews, your fluency will expand rapidly.',
    cefr_level: 'B2',
    part_of_speech: 'verb',
    phonetic: '/ˌpɜːsɪˈvɪər/',
    day_index: 1,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'word-4',
    word: 'Substantiate',
    translation_uz: 'Asoslab bermoq, dalillar bilan tasdiqlamoq',
    definition: 'Provide evidence to support or prove the truth of something.',
    example: 'Always substantiate your arguments with relevant data in IELTS academic essays.',
    cefr_level: 'C1',
    part_of_speech: 'verb',
    phonetic: '/səbˈstænʃieɪt/',
    day_index: 1,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'word-5',
    word: 'Ubiquitous',
    translation_uz: 'Hamma joyda uchraydigan, keng tarqalgan',
    definition: 'Present, appearing, or found everywhere.',
    example: 'Smartphones have become ubiquitous across all districts of Tashkent.',
    cefr_level: 'C1',
    part_of_speech: 'adjective',
    phonetic: '/juːˈbɪkwɪtəs/',
    day_index: 1,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'word-6',
    word: 'Diligent',
    translation_uz: 'Tirishqoq, quntli, mehnatkash',
    definition: 'Having or showing care and conscientiousness in one\'s work or duties.',
    example: 'Diligent practice every morning will help you crack the Band 8 ceiling.',
    cefr_level: 'B1',
    part_of_speech: 'adjective',
    phonetic: '/ˈdɪlɪdʒənt/',
    day_index: 2,
    created_at: '2025-01-02T00:00:00Z',
  },
  {
    id: 'word-7',
    word: 'Meticulous',
    translation_uz: 'Juda sinchkov, har bir mayda detalga e\'tiborli',
    definition: 'Showing great attention to detail; very careful and precise.',
    example: 'Her essay demonstrated meticulous research and precise grammatical control.',
    cefr_level: 'C1',
    part_of_speech: 'adjective',
    phonetic: '/məˈtɪkjələs/',
    day_index: 2,
    created_at: '2025-01-02T00:00:00Z',
  },
  {
    id: 'word-8',
    word: 'Catalyst',
    translation_uz: 'Turtki beruvchi omil, o\'zgarishga sabab bo\'luvchi kuch',
    definition: 'A person or thing that precipitates an event or change.',
    example: 'The opening of the new IT park in Tashkent acted as a catalyst for tech startups.',
    cefr_level: 'B2',
    part_of_speech: 'noun',
    phonetic: '/ˈkætəlɪst/',
    day_index: 2,
    created_at: '2025-01-02T00:00:00Z',
  },
  {
    id: 'word-9',
    word: 'Imperative',
    translation_uz: 'Kechiktirib bo\'lmas zarurat, o\'ta muhim burch',
    definition: 'Of vital importance; crucial.',
    example: 'It is imperative that candidates master topic-specific collocations for Band 7.5+.',
    cefr_level: 'B2',
    part_of_speech: 'adjective',
    phonetic: '/ɪmˈperətɪv/',
    day_index: 2,
    created_at: '2025-01-02T00:00:00Z',
  },
  {
    id: 'word-10',
    word: 'Prevalent',
    translation_uz: 'Keng tarqalgan, hukmron bo\'lgan',
    definition: 'Widespread in a particular area or at a particular time.',
    example: 'Renewable solar initiatives are becoming increasingly prevalent across Uzbekistan.',
    cefr_level: 'B2',
    part_of_speech: 'adjective',
    phonetic: '/ˈprevələnt/',
    day_index: 2,
    created_at: '2025-01-02T00:00:00Z',
  },
  {
    id: 'word-11',
    word: 'Cohesive',
    translation_uz: 'Jipslashgan, uzviy bog\'langan, yaxlit',
    definition: 'Characterized by or causing cohesion; forming a united whole.',
    example: 'A cohesive paragraph utilizes clear referencing pronouns and signposting phrases.',
    cefr_level: 'B2',
    part_of_speech: 'adjective',
    phonetic: '/kəʊˈhiːsɪv/',
    day_index: 3,
    created_at: '2025-01-03T00:00:00Z',
  },
  {
    id: 'word-12',
    word: 'Pragmatic',
    translation_uz: 'Amaliy, real voqelikka asoslangan',
    definition: 'Dealing with things sensibly and realistically in a way that is based on practical considerations.',
    example: 'The administration adopted a pragmatic solution to balance online and classroom learning.',
    cefr_level: 'C1',
    part_of_speech: 'adjective',
    phonetic: '/præɡˈmætɪk/',
    day_index: 3,
    created_at: '2025-01-03T00:00:00Z',
  },
  {
    id: 'word-13',
    word: 'Feasible',
    translation_uz: 'Amalga oshirsa bo\'ladigan, maqbul',
    definition: 'Possible to do easily or conveniently.',
    example: 'Expanding metro lines to suburban Tashkent is financially feasible according to recent projections.',
    cefr_level: 'B2',
    part_of_speech: 'adjective',
    phonetic: '/ˈfiːzəbl/',
    day_index: 3,
    created_at: '2025-01-03T00:00:00Z',
  },
  {
    id: 'word-14',
    word: 'Mitigate',
    translation_uz: 'Yumshatmoq, salbiy oqibatlarini kamaytirmoq',
    definition: 'Make less severe, serious, or painful.',
    example: 'Planting green belts around industrial zones helps mitigate air pollution.',
    cefr_level: 'C1',
    part_of_speech: 'verb',
    phonetic: '/ˈmɪtɪɡeɪt/',
    day_index: 3,
    created_at: '2025-01-03T00:00:00Z',
  },
  {
    id: 'word-15',
    word: 'Paradox',
    translation_uz: 'Qarama-qarshilik, ziddiyatli lekin to\'g\'ri holat',
    definition: 'A seemingly absurd or self-contradictory statement or proposition that when investigated may prove to be well founded or true.',
    example: 'It is a paradox that digital hyper-connectivity can sometimes induce feelings of social isolation.',
    cefr_level: 'C1',
    part_of_speech: 'noun',
    phonetic: '/ˈpærədɒks/',
    day_index: 3,
    created_at: '2025-01-03T00:00:00Z',
  },
  {
    id: 'word-16',
    word: 'Scrutinize',
    translation_uz: 'Sinchkovlik bilan tekshirmoq, sinchiklab ko\'rib chiqmoq',
    definition: 'Examine or inspect closely and thoroughly.',
    example: 'Examiners scrutinize writing submissions for lexical variety and grammatical complexity.',
    cefr_level: 'C1',
    part_of_speech: 'verb',
    phonetic: '/ˈskruːtənaɪz/',
    day_index: 4,
    created_at: '2025-01-04T00:00:00Z',
  },
  {
    id: 'word-17',
    word: 'Commendable',
    translation_uz: 'Tahsinga sazovor, maqtovga loyiq',
    definition: 'Deserving praise and approval.',
    example: 'Jasur made commendable progress, boosting his vocabulary test score from 65% to 92%.',
    cefr_level: 'B2',
    part_of_speech: 'adjective',
    phonetic: '/kəˈmendəbl/',
    day_index: 4,
    created_at: '2025-01-04T00:00:00Z',
  },
  {
    id: 'word-18',
    word: 'Pivotal',
    translation_uz: 'Hal qiluvchi, asosiy ahamiyatga ega',
    definition: 'Of crucial importance in relation to the development or success of something else.',
    example: 'Learning discourse markers played a pivotal role in her IELTS Speaking 8.0 result.',
    cefr_level: 'B2',
    part_of_speech: 'adjective',
    phonetic: '/ˈpɪvətl/',
    day_index: 4,
    created_at: '2025-01-04T00:00:00Z',
  },
  {
    id: 'word-19',
    word: 'Spearhead',
    translation_uz: 'Boshlab bermoq, yetakchilik qilmoq',
    definition: 'Lead an attack or movement; be the leading initiative.',
    example: 'Premier School will spearhead innovative English pedagogical training across Central Asia.',
    cefr_level: 'C1',
    part_of_speech: 'verb',
    phonetic: '/ˈspɪəhed/',
    day_index: 4,
    created_at: '2025-01-04T00:00:00Z',
  },
  {
    id: 'word-20',
    word: 'Ameliorate',
    translation_uz: 'Yaxshilamoq, holatini tuzatmoq',
    definition: 'Make (something bad or unsatisfactory) better.',
    example: 'Structured daily flashcard study can significantly ameliorate test anxiety.',
    cefr_level: 'C1',
    part_of_speech: 'verb',
    phonetic: '/əˈmiːliəreɪt/',
    day_index: 4,
    created_at: '2025-01-04T00:00:00Z',
  }
];

export const SEED_WORD_PROGRESS: WordProgress[] = [
  {
    id: 'wp-1',
    student_id: 'user-student-1',
    word_id: 'word-1',
    box: 4,
    next_review_date: new Date(Date.now() + 86400000 * 5).toISOString().split('T')[0],
    reviews_count: 5,
    mastered: false,
    last_reviewed_at: new Date().toISOString(),
    word: SEED_DAILY_WORDS[0]
  },
  {
    id: 'wp-2',
    student_id: 'user-student-1',
    word_id: 'word-2',
    box: 5,
    next_review_date: new Date(Date.now() + 86400000 * 14).toISOString().split('T')[0],
    reviews_count: 7,
    mastered: true,
    last_reviewed_at: new Date().toISOString(),
    word: SEED_DAILY_WORDS[1]
  },
  {
    id: 'wp-3',
    student_id: 'user-student-1',
    word_id: 'word-3',
    box: 2,
    next_review_date: new Date().toISOString().split('T')[0],
    reviews_count: 2,
    mastered: false,
    last_reviewed_at: new Date().toISOString(),
    word: SEED_DAILY_WORDS[2]
  },
  {
    id: 'wp-4',
    student_id: 'user-student-1',
    word_id: 'word-4',
    box: 1,
    next_review_date: new Date().toISOString().split('T')[0],
    reviews_count: 1,
    mastered: false,
    last_reviewed_at: new Date().toISOString(),
    word: SEED_DAILY_WORDS[3]
  },
  {
    id: 'wp-5',
    student_id: 'user-student-1',
    word_id: 'word-5',
    box: 1,
    next_review_date: new Date().toISOString().split('T')[0],
    reviews_count: 0,
    mastered: false,
    word: SEED_DAILY_WORDS[4]
  }
];

export const SEED_CHAMPIONSHIP: ChampionshipScore[] = [
  {
    id: 'cs-1',
    student_id: 'user-student-2',
    student_name: 'Nodira Karimova',
    month: '2025-09',
    xp: 1890,
    rank: 1,
    lessons_attended: 12,
    homeworks_completed: 8,
    group_name: 'IELTS Intensive Target 7.5+',
    student: SEED_PROFILES[3]
  },
  {
    id: 'cs-2',
    student_id: 'user-student-1',
    student_name: 'Jasur Rustamov',
    month: '2025-09',
    xp: 1420,
    rank: 2,
    lessons_attended: 11,
    homeworks_completed: 6,
    group_name: 'IELTS Intensive Target 7.5+',
    student: SEED_PROFILES[2]
  },
  {
    id: 'cs-3',
    student_id: 'user-student-3',
    student_name: 'Bekzod Toshmatov',
    month: '2025-09',
    xp: 1210,
    rank: 3,
    lessons_attended: 9,
    homeworks_completed: 5,
    group_name: 'General English Intermediate B1',
    student: SEED_PROFILES[4]
  },
  {
    id: 'cs-4',
    student_id: 'user-other-4',
    student_name: 'Dilnoza Murodova',
    month: '2025-09',
    xp: 980,
    rank: 4,
    lessons_attended: 8,
    homeworks_completed: 4,
    group_name: 'General English Intermediate B1',
    student: {
      id: 'user-other-4',
      email: 'dilnoza.m@gmail.com',
      full_name: 'Dilnoza Murodova',
      role: 'student',
      level: 'B1',
      onboarding_completed: true,
      xp: 980,
      streak: 5,
      created_at: '2025-02-12T00:00:00Z'
    }
  },
  {
    id: 'cs-5',
    student_id: 'user-other-5',
    student_name: 'Shoxrux Sobirov',
    month: '2025-09',
    xp: 850,
    rank: 5,
    lessons_attended: 7,
    homeworks_completed: 4,
    group_name: 'Elementary English Starters A2',
    student: {
      id: 'user-other-5',
      email: 'shoxrux.s@gmail.com',
      full_name: 'Shoxrux Sobirov',
      role: 'student',
      level: 'A2',
      onboarding_completed: true,
      xp: 850,
      streak: 4,
      created_at: '2025-02-14T00:00:00Z'
    }
  }
];

export const SEED_BADGES: Badge[] = [
  {
    id: 'b-1',
    student_id: 'user-student-1',
    badge_key: 'streak_7',
    title: 'Consistency Star (7-Day Streak)',
    description: 'Maintained 7 consecutive days of active English study in Tashkent',
    icon: 'Flame',
    awarded_at: '2025-02-14T10:00:00Z'
  },
  {
    id: 'b-2',
    student_id: 'user-student-1',
    badge_key: 'vocab_master_25',
    title: 'Lexical Pioneer',
    description: 'Mastered 25+ advanced academic vocabulary words in Leitner Box 5',
    icon: 'Award',
    awarded_at: '2025-02-16T15:30:00Z'
  },
  {
    id: 'b-3',
    student_id: 'user-student-1',
    badge_key: 'podium_silver',
    title: 'Championship Podium',
    description: 'Ranked in the top 3 on the Premier School Monthly Championship',
    icon: 'Trophy',
    awarded_at: '2025-02-18T18:00:00Z'
  }
];
